### ISSUE TITLE
Package isn't installed correctly

### ISSUE THREAD

**Issue by BarryThePenguin** [koistya/nuget-gulp#2]
I noticed that the package doesn't install correctly when package restore is used.

It looks like the package adds two files, 'gulp' and 'gulp.cmd' to 'packages/Node.js.0.10.xx'. I don't think nuget packages should be modifying the contents of other packages like this. Maybe @giggio or @whyleee could give some assistance, or checkout their packages to see how they handle build commands https://github.com/giggio/npm-nuget

**Comment by giggio** [comment]
The npm/bower/grunt projects on nuget are all becoming obsolete as ASP.NET moves to a more modern platform with ASP.NET 5. Npm, Bower, Grunt and Gulp are built in. I don't see the point of maintaining these packages anymore.
Anyway, from what I saw, they are using npm install --save-dev, which seems correct. Somebody should investigate further.

**Comment by BarryThePenguin** [comment]
Yes. It's quite exciting. Thanks anyway!

**Comment by giggio** [comment]
Yes it is! \o/
